In [1]:
!pip install numpy


In [2]:
!pip install pandas


In [3]:
import numpy as np

In [4]:
import pandas as pd


In [5]:
print(np.__version__)
print(pd.__version__)

2.5.3
3.0.6


In [6]:
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [7]:
arr1 = np.array(list1)
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
list1=[1,2,3,4,5,6]
list2=[7,8,9,10,11,12]

arr_2= np.array([list1,list2])

In [9]:
print(arr_2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
import numpy as np

list1 = [1, 2, 3, 4, 5, 6]
list2 = [7, 8, 9, 10, 11, 12]
list3 = [13, 14, 15, 16, 17, 18]  # now 6 elements

# 2D array of shape (3, 6):
arr_2d = np.array([list1, list2, list3])
print(arr_2d)

# Or if you intentionally wanted a 3D array of shape (1, 3, 6):
arr_3d = np.array([[list1, list2, list3]])
print(arr_3d.shape)  # (1, 3, 6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(1, 3, 6)


In [14]:
print(arr_2d.ndim)
print(arr_3d.ndim)


2
3


In [ ]:
#Create 1D & 2D Arary and find its attributes

In [17]:
arr_1D = np.array([1,2,3,4,5,6])
print("Shape",arr_1D.shape)
print("Size",arr_1D.size)
print("dType",arr_1D.dtype)
print("ndim",arr_1D.ndim)
print(arr_1D)

arr_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Shape",arr_2D.shape)
print("Size",arr_2D.size)
print("dType",arr_2D.dtype)
print("ndim",arr_2D.ndim)
print(arr_2D)

Shape (6,)
Size 6
dType int64
ndim 1
[1 2 3 4 5 6]
Shape (2, 5)
Size 10
dType int64
ndim 2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
zero_arr = np.zeros((2,3))
print(zero_arr)

one_arr = np.ones((2,3))
print(one_arr)

full_arr = np.full((3,2),18)
print(full_arr)

id_arr = np.eye(4)
print(id_arr)

print(np.empty(4))

print(np.arange(1,10,2))

print(np.linspace(1,10,4))

r_arr = np.random.rand(4,2)
print(r_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[18 18]
 [18 18]
 [18 18]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1. 1.]
[1 3 5 7 9]
[ 1.  4.  7. 10.]
[[0.8295684  0.55447995]
 [0.45896101 0.78240731]
 [0.90303955 0.55087409]
 [0.71698853 0.49335615]]


In [20]:
reshaped1= r_arr.reshape((2,4))
print(reshaped1)

[[0.8295684  0.55447995 0.45896101 0.78240731]
 [0.90303955 0.55087409 0.71698853 0.49335615]]


In [21]:
reshaped2= id_arr.reshape((8,2))
print(reshaped2)

[[1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]


In [22]:
print(reshaped2.flatten())


[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [23]:
print(np.vstack((zero_arr,one_arr)))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(np.hstack((zero_arr,one_arr)))

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [27]:
print(np.hsplit(reshaped1,2))

[array([[0.8295684 , 0.55447995],
       [0.90303955, 0.55087409]]), array([[0.45896101, 0.78240731],
       [0.71698853, 0.49335615]])]


In [28]:
# Angles in degrees
degrees = np.array([0, 30, 45, 60, 90])

# 1. Convert degrees to radians (Crucial step)
radians = np.deg2rad(degrees)
# Alternatively: radians = degrees * (np.pi / 180)

# 2. Sine, Cosine, Tangent
sin_vals = np.sin(radians)
cos_vals = np.cos(radians)
tan_vals = np.tan(radians)

# 3. Secant (sec = 1 / cos)
sec_vals = 1 / cos_vals

# Display results
print("Degrees: ", degrees)
print("Radians: ", np.round(radians, 4))
print("Sine:    ", np.round(sin_vals, 4))
print("Cosine:  ", np.round(cos_vals, 4))
print("Tangent: ", np.round(tan_vals, 4))
print("Secant:  ", np.round(sec_vals, 4))

Degrees:  [ 0 30 45 60 90]
Radians:  [0.     0.5236 0.7854 1.0472 1.5708]
Sine:     [0.     0.5    0.7071 0.866  1.    ]
Cosine:   [1.     0.866  0.7071 0.5    0.    ]
Tangent:  [0.00000000e+00 5.77400000e-01 1.00000000e+00 1.73210000e+00
 1.63312394e+16]
Secant:   [1.00000000e+00 1.15470000e+00 1.41420000e+00 2.00000000e+00
 1.63312394e+16]
